// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int greaterThanHalf = 0;
		int lessThanHalf = 0;
		double rand = 0.0;
		double ratio = 0.0;
		for(int i = 0; i < n; i++){
			rand = Math.random();
			if(rand > 0.5){
				greaterThanHalf++;
			}
			else{
				lessThanHalf++;
			}
		}
		System.out.println("> 0.5: " + greaterThanHalf + " times");
		System.out.println("<= 0.5: " + lessThanHalf + " times");
		if(lessThanHalf != 0.0){
			ratio = (double)greaterThanHalf / lessThanHalf;
			System.out.println("Ratio: " + ratio);
		}
	}
}
